### ISSUE TITLE
Feature: Loot single item instead of all at once

### ISSUE THREAD

**Issue by EricksOliveira** [azerothcore/mod-aoe-loot#18]
### Describe your feature request or suggestion in detail

When looting the creature, choose only 1 item and it will only pull that item from all NPCs, Example: Wool Cloth ID 2592!

**Comment by pangolp** [comment]
Hello, thanks for the suggestion. Once the module is improved and has all the functionalities well polished, it would be possible to add a variable within the configuration file, which, by default, is not enabled and when doing so, only raises the item as you mention.

**Comment by kamila231993** [comment]
It doesn't work properly yet, he gathers all the objects from adds, he has to bring only the objects you select, of course, not all of them

**Comment by pangolp** [comment]
Analyzing the topic a little, and seeing that I have not yet managed to finish the module, but I am making some progress that will possibly allow me to finish it soon, I get the feeling that this topic should be in another module. Could it be compatible with this module? Yeah. And by default, it should be disabled. For the module to work, as originally intended, which is to obtain all the items from the nearby bodies. So later, once the module is functional, we will debate whether it is better to move this topic to another module, because in itself, it will have to have a special logic. Because as server administrators, we cannot debate what item we want a player to get or not. We would have to let them choose, and for that, they would have to respond with a series of commands that would allow them to view, add, delete and empty the list. Because the option to eliminate it, as administrators, is simple, but we do not know what each person wants to farm, and we could unintentionally harm someone who wants to obtain an item and we do not let them. Therefore, although they can be shareable, I think the best thing would be to finish this module, make it work, and then think of another module, which perhaps can perform this function in the future.

**Comment by pangolp** [comment]
Due to recent changes within the module, I really don't know if this is possible to implement. I think this functionality could easily be developed in another module, where it can be specified which items are removed and which items remain on the body or are removed differently from the bodies. Because if they remain on the bodies, it could cause the person to be unable to skin the creature until all the creature's content is gone.

**Comment by EricksOliveira** [comment]
Yes. I hadn't thought about it that way. I think it will have to be better reformulated.

**Comment by pangolp** [comment]
Perhaps the best thing would be to close the issue then. (If you think it's convenient)

**Comment by EricksOliveira** [comment]
Perfect for me. And I believe others agree too!

**Comment by pangolp** [comment]
> Perfect for me. And I believe others agree too!

Sorry, but I can't understand your answer. I need more context.

**Comment by Helias** [comment]
He agrees to close this issue, so I am closing it
Thanks both!

If there is anything else to discuss about this, let's open again the issue.
