### ISSUE TITLE
Bug: When skin a creature , not loot is received

### ISSUE THREAD

**Issue by Tilenozz** [azerothcore/mod-aoe-loot#19]
### Current Behaviour

Hi !
When skinning , no loot is given. Even no chat , item in bag not appear/increase

https://youtu.be/4wriFynRneg

### Expected Behaviour

Get relative leather loot

### Steps to reproduce the problem

1. Creature tested
2. Skin
3. no loot given, even on inventory , item is not created / added

### AC rev. hash/commit

AC> .server debug
AC> AzerothCore rev. 03d06da87b85+ 2023-12-15 09:43:24 -0300 (master branch) (Un                                        ix, RelWithDebInfo, Static)
Connected players: 0. Characters in world: 0.
Connection peak: 1.
Server uptime: 6 hour(s) 51 minute(s) 4 second(s)
Update time diff: 1ms, average: 2ms.
Using SSL version: OpenSSL 3.0.2 15 Mar 2022 (library: OpenSSL 3.0.2 15 Mar 2022                                        )
Using Boost version: 1.74.0
Using CMake version: 3.22.1
Using MySQL version: 80035
Found MySQL Executable: /usr/bin/mysql
Compiled on: Linux 5.15.0-91-generic
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in /home/azeroth-server/data/maps. Total size: 291014951                                         bytes
vmaps directory located in /home/azeroth-server/data/vmaps. Total size: 65813072                                        1 bytes
mmaps directory located in /home/azeroth-server/data/mmaps. Total size: 21929108                                        44 bytes
Default DBC locale: enUS.
All available DBC locales: enUS
Using World DB: ACDB 335.10-dev
Latest LoginDatabase update: 2023_04_24_00.sql
Latest CharacterDatabase update: mod_solo_craft.sql
Latest WorldDatabase update: col_reward_items.sql
LoginDatabase queue size: 0
CharacterDatabase queue size: 0
WorldDatabase queue size: 0
> List enable modules:
- mod-account-mounts
- mod-aoe-loot
- mod-cfbg
- mod-chat-login
- mod-congrats-on-level
- mod-eluna
- mod-learn-spells
- mod-multi-client-check
- mod-weekendbonus

### Operating system

Ubuntu 20.04

**Comment by pangolp** [comment]
Hello, the module is not finished yet. However, the time that bodies remain in the world before being stripped must be increased. Because naturally, by stripping them one by one, it gives enough time, since the body disappears when it no longer has any loot. On the world server, you will find an option to increase the time a creature is in the world after it has no more loot. Regarding the skinning skill, I don't know how many points it has, but it is normal for errors to occur while the skill is raised.

**Comment by pangolp** [comment]
```
#
#    Corpse.Decay.NORMAL
#    Corpse.Decay.RARE
#    Corpse.Decay.ELITE
#    Corpse.Decay.RAREELITE
#    Corpse.Decay.WORLDBOSS
#        Description: Time (in seconds) until creature corpse will decay if not looted or skinned.
#        Default:     60   - (1 Minute, Corpse.Decay.NORMAL)
#                     300  - (5 Minutes, Corpse.Decay.RARE)
#                     300  - (5 Minutes, Corpse.Decay.ELITE)
#                     300  - (5 Minutes, Corpse.Decay.RAREELITE)
#                     3600 - (1 Hour, Corpse.Decay.WORLDBOSS)

Corpse.Decay.NORMAL    = 60
Corpse.Decay.RARE      = 300
Corpse.Decay.ELITE     = 300
Corpse.Decay.RAREELITE = 300
Corpse.Decay.WORLDBOSS = 3600

#
#    Rate.Corpse.Decay.Looted
#        Description: Multiplier for Corpse.Decay.* to configure how long creature corpses stay
#                     after they have been looted.
#         Default:    0.5

Rate.Corpse.Decay.Looted = 0.5
```

If you manipulate these variables, it will give you more time to skin the creatures. By default, since you only get 1 body at a time, there is enough time to skin them all. Being an area loot, everyone has the same time, which is why it doesn't give you enough time to skin them all.

**Comment by pangolp** [comment]
Add the information that I mentioned in the README of the repository. If you think the topic is incorrect, let me know, and we'll reopen the topic.

**Comment by Tilenozz** [comment]
Ciao Walter,
i tried this : 

Corpse.Decay.NORMAL    = 600
Corpse.Decay.RARE      = 3000
Corpse.Decay.ELITE     = 3000
Corpse.Decay.RAREELITE = 3000
Corpse.Decay.WORLDBOSS = 36000
Rate.Corpse.Decay.Looted = 0.5

This : 

Corpse.Decay.NORMAL    = 600
Corpse.Decay.RARE      = 3000
Corpse.Decay.ELITE     = 3000
Corpse.Decay.RAREELITE = 3000
Corpse.Decay.WORLDBOSS = 36000
Rate.Corpse.Decay.Looted = 5.0

And always same result : if there are no items to loot u can skin the cerature,otherwise u loot items but cannot skin

**Comment by pangolp** [comment]
> And always same result : if there are no items to loot u can skin the creature,otherwise u loot items but cannot skin

Perfect then, I reopen the topic and review it more carefully later. The thing is that the module is still in development, it is not finished, we have made many improvements, but sometimes, perhaps we miss some things. It happens that since he didn't respond to me, I thought the topic was already closed. Thanks for the report.

**Comment by pangolp** [comment]
I'm doing a couple of tests, and I think I found the problem. Trying to prevent them from being infinite creatures, I made a mistake and used code that I shouldn't have used. If it passes the tests, I merge them, and ask you to download the module or the changes again, so I can do the tests again.

**Comment by pangolp** [comment]
To test correctly, please disable auto-stripping. Anyway, when you click on an item or gold, you will automatically get them all. Because in the video I see, or I thought I saw, he sometimes gave you the item, but not always. Likewise, what I deleted should never have been there, but I was trying to prevent a leather exploit from occurring.

**Comment by Tilenozz** [comment]
Hello ,

i tested after fix , here the [result](https://youtu.be/lwAi_ofwgR8)

**Comment by pangolp** [comment]
It looks good from what I can see. What I don't understand is why skinning fails so much, given that you are at a high level, because it is seen that the experience obtained is green. But even so, it requires at least 2 attempts to obtain the material. But that is no longer an area loot issue, that is now an emulator issue.

**Comment by Tilenozz** [comment]
next video is without module active. ( ofc skinn 375 ) . It s quite strange without , no fail at all.
https://youtu.be/Q0BFWQgSMIk

**Comment by pangolp** [comment]
> next video is without module active. ( ofc skinn 375 ) . It s quite strange without , no fail at all.
> https://youtu.be/Q0BFWQgSMIk

Is the problem then with the module? How strange, it shouldn't be. But it's good to know. I thought it was the emulator. We will have to continue working then.

**Comment by pangolp** [comment]
I realized that the logic of the module is wrong, it is possible that for that reason, the skinning is also failing, so I am doing tests, and modifying a couple of things, to see if I can make it work once and for all. right way.

**Comment by pangolp** [comment]
I think that with the next fix, it has to be solved.
Try it and let me know if it works.
As soon as I pass the tests, I merge it.
I've been testing it, and it seems to work.
