### ISSUE TITLE
Module not working :(

### ISSUE THREAD

**Issue by Griptor** [azerothcore/mod-aoe-loot#8]
Hi there
have a fresh compile from.

https://github.com/trickerer/AzerothCore-wotlk-with-NPCBots

I have changed the module config to 
AOELoot.Enable = 1

Sadly the mod does nothing when I type into the chat window in-game
.aoeloot - no such command exists.

**Comment by Shoro2** [comment]
Its because these files are empty, dunno why this is listed as mod

**Comment by Griptor** [comment]
Lol I see
I got this to work but it's alittle off
https://github.com/azerothcore/azerothcore-wotlk/compare/master...acidmanifesto:Azerothcore-AOE-Branch

**Comment by pangolp** [comment]
The module is currently not working. We are working to make it happen, but at the moment it is not functional. In fact, if I remember correctly, in the README.md file, it says exactly that, that we are still working to make it work. Some of the code is working, however, we still need to continue working on some aspects of it, and make some hooks in the emulator, so that it can be used, but we have had some progress so far.
